### PR TITLE
Multiple seats

### PR DESCRIPTION
**Pull request by omarhogni**
Added the ability to have multiple seats, this allows f.e. weston screenshare and a local touch input to work at the same time.

### CODE REVIEW

**Comment by omarhogni** [comment]
Currently there are issues with displaying the cursor correctly when vnc connections are added and removed.

**Comment by HidenoriMatsubayashi** [comment]
Thank you for sending this PR.

Could you please update [AUTHORS](https://github.com/sony/flutter-embedded-linux/blob/master/AUTHORS) too?

Also, it's unclear whether we can contribute this software to flutter/engine, but do you agree to delegate all rights related to this PR to Sony?

**Comment by HidenoriMatsubayashi** [comment]
Also, could you please add a signoff (DCO) to the last commit you made?

**Comment by omarhogni** [comment]
I have modified the `AUTHORS` file and added the sign-off. I am fine with delegating all rights related to this PR.

**Review by HidenoriMatsubayashi — APPROVED** [review]
LGTM. Thanks a lot!

**Comment by HidenoriMatsubayashi** [comment]
This PR should fix #409 and #341

**Pull request merged**
