### PR TITLE
Add libuv support as a replacement of systemd + some CMake fixes

### PR DESCRIPTION
**Pull request by Thor-x86**
This PR solves:
- https://github.com/sony/flutter-embedded-linux/issues/419
- https://github.com/sony/flutter-embedded-linux/issues/402

For further commit description regarding libuv support, see https://github.com/sony/flutter-embedded-linux/commit/7928671070f6b0cd2cda380e8818535bfc7871f1.

### CODE REVIEW

**Comment by HidenoriMatsubayashi** [comment]
Thank you for sending this PR. 

I would like to confirm one thing regarding this PR. It's unclear whether we can contribute this software to flutter/engine, but do you agree to delegate all rights related to this PR to Sony?

**Comment by Thor-x86** [comment]
>  do you agree to delegate all rights related to this PR to Sony?

Yeah sure! As long as it keep open sourced :)

**Comment by HidenoriMatsubayashi** [comment]
Thank you.

Please check the CI failure.

**Comment by Thor-x86** [comment]
Sorry, the commit https://github.com/sony/flutter-embedded-linux/commit/13b92066241cd70db97b415557c1551acaf2c30b was removed because I forgot to exclude the `src/third_party/*`. Wonder why you didn't use [git submodule][1] for the source code dependencies.

[1]: https://github.blog/2016-02-01-working-with-submodules/

**Comment by Thor-x86** [comment]
I discovered a quirk on `clang-format`: **its output won't be consistent between clang-format versions**. Ubuntu Jammy has clang v14 and Arch Linux has clang v17. Their formatter always output different result. I'm still looking for a solution how to make `.clang-format` be universal. Because this problem also affects Debian users since they prefer to stay on most stable version.

For the CMake, this is my mistake. I supposed to consider to use `STREQUAL` instead of `EQUAL` due to compatibility issue.

**Review by HidenoriMatsubayashi — APPROVED** [review]
LGTM.

> I'm still looking for a solution how to make .clang-format be universal. Because this problem also affects Debian users since they prefer to stay on most stable version.

Thank you. I'll wait for your comment about this.

**Comment by Thor-x86** [comment]
> I'll wait for your comment about this.

It's going to be a new PR in the future. For now, you can safely merge the changes.

**Comment by HidenoriMatsubayashi** [comment]
Okay, thank you so much.

**Pull request merged**
