### PR TITLE
Added marshalling to main thread messages sent from native side

### PR DESCRIPTION
**Pull request by Kofhein**
This commit adds marshalling of messages sent from native side to be executed on main thread

### CODE REVIEW

**Comment by HidenoriMatsubayashi** [comment]
Thank you for this PR, @Kofhein.

Could you please update [AUTHORS](https://github.com/sony/flutter-embedded-linux/blob/master/AUTHORS) too? Also, it's unclear whether we can contribute this software to flutter/engine, but do you agree to delegate all rights related to this PR to Sony?

**Comment by Kofhein** [comment]
@HidenoriMatsubayashi , AUTHORS updated, yes, I agree

**Comment by HidenoriMatsubayashi** [comment]
Thank you, Kofhein.

**Review by HidenoriMatsubayashi — APPROVED** [review]
LGTM. Thank you.

**Pull request merged**
