### PR TITLE
Update embedder.h to the latest version

### PR DESCRIPTION
**Pull request by HidenoriMatsubayashi**
Update [embedder.h](https://github.com/flutter/engine/blob/master/shell/platform/embedder/embedder.h) to the latest version. 

@Mai-Matsuura I'm sorry but could you check if operating correctly with this change and the latest `libflutter_engine.so`?

### CODE REVIEW

**Comment by Mai-Matsuura** [comment]
> @Mai-Matsuura I'm sorry but could you check if operating correctly with this change and the latest `libflutter_engine.so`?

Which board and backend combination should I test?

**Comment by HidenoriMatsubayashi** [comment]
It's OK on x64 desktops.

**Comment by Mai-Matsuura** [comment]
@HidenoriMatsubayashi  
I could run the Flutter app with the Wayland backend using the latest `libflutter_engine.so`.

**Comment by HidenoriMatsubayashi** [comment]
Thanks!

**Pull request merged**
