### PR TITLE
Fix weston desktop shell version issue

### PR DESCRIPTION
**Pull request by HidenoriMatsubayashi**
I fixed the following issues
- https://github.com/sony/flutter-embedded-linux/issues/3
- https://github.com/sony/flutter-embedded-linux/issues/102
- https://github.com/sony/flutter-embedded-linux/issues/4#issuecomment-828121126

### CODE REVIEW

**Comment by HidenoriMatsubayashi** [comment]
@taka-okayama Can you review the PR?

**Comment by taka-okayama** [comment]
@HidenoriMatsubayashi 

I think we need to update status([Tested devices section in README.md](https://github.com/sony/flutter-embedded-linux#tested-devices)).  
weston(>=8.0.0) is not available in [Ubuntu 18.04LTS by default](https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=libweston&searchon=names).

**Comment by HidenoriMatsubayashi** [comment]
We need to use libweston in this case, but don't always necessarily have to use Weston. There are many Wayland compositors. `weston-desktop-shell` is one of the build options, and isn't the main target. Therefore, I don't think so.

**Review by taka-okayama — APPROVED** [review]
I understand. I'll just leave a comment here so that it can be found in the search.

Note: If you want to use Weston on Ubuntu 18.04LTS, please make sure you have version 8.0.0 or higher.
The package repository of Ubutnu 18.04LTS does not provide the desired version of weston.

**Comment by HidenoriMatsubayashi** [comment]
Cool!

**Pull request merged**
